In [1]:
import tester
import dataframe_image as dfi
import pandas as pd
import matplotlib

In [2]:
tester.genDFforGene('nhaR')

In [3]:
tester.genDFforGene('yaaA')

In [4]:
tester.genDFforGene('nhaA')

In [5]:
tester.genDFforGene('thrA')

In [6]:
tester.genDFforGene('thrC')

In [7]:
tester.genDFforGene('thrB')

In [8]:
tester.genDFforGene('satP')

In [9]:
tester.genDFforGene('dnaJ')

In [10]:
tester.genDFforGene('ribF')

In [11]:
tester.genDFforGene('mog')